"""Deterministic Company OS bootstrap runtime."""

from .config import CompanyConfig, load_company_config, load_validated_company_config
from .context_assembly import (
    CapsuleRefRejection,
    CapsuleSelectionReason,
    ContextAssembly,
    ContextAssemblyPolicy,
    ContextPlan,
    StaleCapsulePolicy,
    assemble_context,
)
from .attempts import AttemptReport, AttemptResult, finalise_attempt
from .authority import (
    AUTHORITY_SNAPSHOT_VERSION,
    AuthoritySource,
    ExecutionAuthoritySnapshot,
    authority_projection,
)
from .context_expansion import (
    ContextExpansionDecision,
    ContextExpansionLedger,
    ContextExpansionRequest,
    ContextRefRejection,
    ExpansionOutcome,
    effective_context_fingerprint,
)
from .context_cache import CacheLookup, CacheOutcome, CacheStats, ContextCache
from .context_expansion_policy import decide_context_expansion
from .context_units import (
    CONTEXT_UNIT_VERSION,
    DEFAULT_COMPRESSION_THRESHOLD_CHARS,
    CacheStability,
    CompressedBody,
    CompressionKind,
    ContextBundle,
    ContextUnit,
    UnitAuthority,
    UnitKind,
    bundle_of,
    cache_stability,
    compress,
    content_digest,
    expand,
    recompress,
    unit_from_source,
)
from .errors import LifecycleError
from .evidence_records import (
    EVIDENCE_RECORD_VERSION,
    EvidenceLedger,
    EvidenceOutcome,
    ExecutionEvidence,
    ExecutionEvidenceKind,
)
from .execution_store import (
    AttemptRecord,
    AuthorityRecord,
    ExecutionRecordPointer,
    ExecutionStore,
    ExecutionStoreError,
    PacketRecord,
)
from .lifecycle import (
    Escalation,
    ExecutionPreparation,
    LifecycleState,
    TaskPlan,
    contract_from_registry,
    plan_task,
)
from .packets import (
    COMPLETION_PROTOCOL,
    ExecutorHint,
    SessionPacket,
    build_session_packet,
)
from .path_scope import PathScope, PathScopeVerdict
from .receipts import (
    ReceiptUsage,
    ReceiptValidation,
    ReportedTest,
    SessionReceipt,
    validate_receipt,
)
from .routing import EmployeeMatch, RoutingResult, match_capabilities
from .session_adapter import (
    ExpandedSession,
    IngestedSession,
    ManualExternalSessionAdapter,
    PreparedSession,
)
from .specification import ContextRequirements, TaskSpecification
from .tasks import HandoffArtifact, TaskAssignment, TaskStatus, UsageRecordPointer
from .usage_store import ResourceUsageStore, UsageStoreError
from .transport import EXPANSION_INSTRUCTIONS, SessionTransportBundle

__all__ = [
    "AUTHORITY_SNAPSHOT_VERSION",
    "AttemptRecord",
    "AttemptReport",
    "AttemptResult",
    "AuthorityRecord",
    "AuthoritySource",
    "COMPLETION_PROTOCOL",
    "CONTEXT_UNIT_VERSION",
    "CacheLookup",
    "CacheOutcome",
    "CacheStability",
    "CacheStats",
    "CapsuleRefRejection",
    "CapsuleSelectionReason",
    "CompanyConfig",
    "CompressedBody",
    "CompressionKind",
    "ContextAssembly",
    "ContextAssemblyPolicy",
    "ContextBundle",
    "ContextCache",
    "ContextExpansionDecision",
    "ContextExpansionLedger",
    "ContextExpansionRequest",
    "ContextPlan",
    "ContextRefRejection",
    "ContextRequirements",
    "ContextUnit",
    "DEFAULT_COMPRESSION_THRESHOLD_CHARS",
    "EVIDENCE_RECORD_VERSION",
    "EXPANSION_INSTRUCTIONS",
    "EmployeeMatch",
    "Escalation",
    "EvidenceLedger",
    "EvidenceOutcome",
    "ExecutionAuthoritySnapshot",
    "ExecutionEvidence",
    "ExecutionEvidenceKind",
    "ExecutionPreparation",
    "ExecutionRecordPointer",
    "ExecutionStore",
    "ExecutionStoreError",
    "ExecutorHint",
    "ExpandedSession",
    "ExpansionOutcome",
    "HandoffArtifact",
    "IngestedSession",
    "LifecycleError",
    "LifecycleState",
    "ManualExternalSessionAdapter",
    "PacketRecord",
    "PathScope",
    "PathScopeVerdict",
    "PreparedSession",
    "ReceiptUsage",
    "ReceiptValidation",
    "ReportedTest",
    "ResourceUsageStore",
    "RoutingResult",
    "SessionPacket",
    "SessionReceipt",
    "SessionTransportBundle",
    "StaleCapsulePolicy",
    "TaskAssignment",
    "TaskPlan",
    "TaskSpecification",
    "TaskStatus",
    "UnitAuthority",
    "UnitKind",
    "UsageRecordPointer",
    "UsageStoreError",
    "assemble_context",
    "authority_projection",
    "build_session_packet",
    "bundle_of",
    "cache_stability",
    "compress",
    "content_digest",
    "contract_from_registry",
    "decide_context_expansion",
    "effective_context_fingerprint",
    "expand",
    "finalise_attempt",
    "load_company_config",
    "load_validated_company_config",
    "match_capabilities",
    "plan_task",
    "recompress",
    "unit_from_source",
    "validate_receipt",
]
