extends Node3D

## The Neon Marble Machine visual proof: start platform, mixing bowl, bridge.
##
## A sibling of `race_scene.gd`, not a change to it. The two play the same
## replay format through the same offline renderer and keep the same contract
## - Godot is presentation only, every position comes out of the file, nothing
## here runs physics or race rules - and they disagree about everything else,
## because they are answers to different questions.
##
## `race_scene.gd` draws whatever course it is handed. It has to: it plays
## courses it has never seen, so it recognises a piece by its role and its
## angle and can know nothing about what the course *is*. That generality is
## exactly what caps how three-dimensional it can look. A funnel drawn as a
## set of angled beams is a set of angled beams.
##
## This file draws one machine, and is told where its parts are. The course
## exports a centre, a radius and a handful of planes in `course.metadata`,
## and the bowl mesh, the presentation heights and the camera are all built
## from those numbers. That is what buys the third dimension: a bowl can be a
## bowl instead of two ramps, because something knows it is a bowl.
##
## ## The presentation mapping
##
## The simulation is two-dimensional and is never touched. Simulation x
## becomes world X and simulation y becomes world Z, exactly as in the race
## scene - one to one, no warp, so two racers touching in the simulation are
## touching on screen and no pair can be drawn intersecting that is not
## intersecting.
##
## The whole of the third axis is derived, by one function:
##
##     deck_height(sim_x, sim_y) -> world Y
##
##         start        flat, the highest surface in the machine
##         chute        eased descent to the bowl rim
##         bowl         H_RIM - BOWL_DEPTH * profile(rho)
##         throat       eased descent below the drain
##         bridge       gentle descent, and a shallow finish beyond it
##
## `rho` is the racer's distance from the bowl centre in the simulation
## plane, over the bowl radius. That is the whole trick of the bowl: a racer
## far from the centre is high on the wall, a racer near the centre is at the
## floor, and a marble that shoots across the basin and up the other side
## does on screen exactly what a marble in a bowl does. Free fall inside the
## disc reads as a slide down the inner surface, because falling reduces the
## distance to the centre.
##
## Every surface in the machine is generated by evaluating the same function
## the racers are placed by. That is not tidiness - it is the only way to
## guarantee the acceptance criterion. A racer sits at `deck_height` plus its
## radius and the mesh under it *is* `deck_height`, so a racer can never
## float above the bowl or sink into it however the physics behaves.
##
## ## Everything is a pure function of the replay tick
##
## As in the race scene: the offline renderer seeks to `frame / fps` and
## draws. Nothing here integrates, accumulates or randomises. The camera's
## framing, the shutter's animation and the racer transforms are all computed
## from the playhead, so two renders of one replay are identical.

const NeonMaterials := preload("res://scripts/neon_materials.gd")
const NeonFlags := preload("res://scripts/neon_flags.gd")

# The single place where logical simulation pixels become Godot world units.
# The same figure every other scene in this project uses.
const PIXELS_PER_UNIT := 100.0

# --- presentation heights -------------------------------------------------
#
# In world units, and the reason the machine has a silhouette at all. The
# brief asks for three sections at visibly different heights; these are those
# heights, and the nine units between the platform deck and the end of the
# bridge are what a tilted lens turns into a stack of levels.
#
# They were half this to begin with and the machine read as one continuous
# pale slope from the deck to the bowl - a ten degree ramp is a floor, not a
# level change. At the drop below, the chute leaves the platform at
# twenty-three degrees and has a lit edge, a thickness and a shadow of its
# own, and the bowl sits visibly beneath the platform rather than beside it.
const H_START := 0.0
const H_RIM := -2.60
const BOWL_DEPTH := 2.60
const H_THROAT := -6.20
const H_BRIDGE_END := -9.20
const H_FINISH_DROP := 0.55

# The bowl profile, in bowl-local radius.
#
# `FLOOR_RHO` is where the flat floor around the drain ends and the wall
# begins to rise. It is wider than the drain itself so a racer waiting its
# turn at the hole stands on a floor rather than balancing on a slope.
#
# `FLANGE_OUTER` is the outer edge of the flat lip, and it exists because a
# racer arriving over the rim is at a radius slightly past 1.0 - the measured
# worst case on the reference replay is 1.11 - and every one of those has to
# have something under it. Anything further out is clamped onto the lip.
const FLOOR_RHO := 0.26
const FLANGE_OUTER := 1.16
const BOWL_PROFILE_POWER := 1.9

# --- the camera -----------------------------------------------------------

# Modest, because a wide lens on a portrait frame stretches the corners and
# makes a marble at the edge of the bowl read as the wrong shape.
const CAM_FOV := 40.0
# Chosen by looking, not by argument. `tools/neon_proof.py --cameras` renders
# the same four moments through this scene at 42, 48, 52 and 56, and
# `--race-elevation=` overrides this at render time so the sweep comes out of
# one build of one scene from one replay.
#
# 42 puts the most drama into the bowl's outer wall and loses the bridge: the
# S-curve is small, distant, and its pillars are hidden behind the deck they
# hold up, so the one thing that stretch exists to prove does not read. 56
# recovers all of that and starts costing the bowl - the dish flattens out
# towards a plan of itself. 52 keeps the bowl an oval with a visible far wall
# *and* stands the bridge above its own shadow with the posts in view, which
# are the two things the brief asks a frame to answer. See
# `docs/neon_machine_visual_proof.md` for the comparison stills.
const CAM_ELEVATION := 52.0
# Clearance past the course wall at the nearest visible ground point, which
# is where a tilted frustum is narrowest against the ground.
const CAM_EDGE_MARGIN := 0.70
# How far ahead of the exported camera track the lens is aimed, in course
# pixels. The track frames the leading group at 42% of a 1920px window, so
# the leaders sit at camera_y + 806; aiming just short of them keeps the
# leaders below centre and fills the top of the frame with what they are
# about to reach.
const CAM_LEAD := 780.0
# Added to the lead once the field is on the bridge, so the shot moves along
# the S-curve rather than holding the emptying bowl in the foreground.
const LEAD_BRIDGE := 520.0
const CAM_AIM_LIFT := 0.95

# The move, as one flowing shot. Each term is a smoothstep of the aim's
# course height, so the whole thing is a pure function of the playhead and
# seeking anywhere gives the same framing.
#
# Where each phase begins and ends is derived from the machine rather than
# written down. These are the offsets that place the crossings: the shot starts
# closing in a little before the gate, commits to the bowl a little after the
# rim, and turns along the bridge a little after it begins. The first version
# had three Vector2s of course pixels in it, which was three magic numbers
# that happened to match this course and would silently stop matching the
# hero one.
const PHASE_RELEASE_LEAD := 40.0
const PHASE_BOWL_INSET := 150.0
const PHASE_BRIDGE_INSET := 120.0
const PHASE_BRIDGE_SHARE := 0.625
const DOLLY_WIDE := 0.15
const DOLLY_BOWL := 0.03
const DOLLY_BRIDGE := 0.03
const DIP_BOWL := 3.0                    # degrees of elevation given up
const DIP_BRIDGE := 1.0
const LIFT_BOWL := 0.35

# A slow orbit: eight degrees over the whole shot, applied to the camera
# position and not to the aim, so the machine stays centred while the near
# structure and the far structure sweep across the frame at visibly different
# rates. That difference is the parallax cue, and the cheapest one there is.
const ORBIT_FROM := -3.5
const ORBIT_TO := 4.5
const ORBIT_SPAN := Vector2(600.0, 3400.0)

# --- the room -------------------------------------------------------------

const VOID_FLOOR_Y := -19.0
const ROOM_OVERRUN_TOP := 1500.0
const ROOM_OVERRUN_BOTTOM := 2400.0
# Two ranks of columns outside the machine. The near rank has to clear the
# bowl's lip, which reaches 5.45 units from the centre line.
const COLUMN_FAR_X := 15.5
const COLUMN_NEAR_X := 11.0
const COLUMN_FAR_SPACING := 5.4
const COLUMN_NEAR_SPACING := 11.0
const COLUMN_FAR_SIZE := Vector3(0.85, 13.0, 0.85)
const COLUMN_NEAR_SIZE := Vector3(1.15, 15.0, 1.15)

# --- decks ----------------------------------------------------------------

# A deck is a solid beam, and how deep it is decides whether it reads as an
# object. These are generous on purpose: the brief asks for visible track
# thickness, and at thirty units from the lens a deck any shallower than this
# is a line.
const DECK_THICKNESS := 0.42
const DECK_MARGIN := 32.0        # course px the deck reaches past the walls
const DECK_STEP := 26.0          # course px between deck cross-sections
const RAIL_WIDTH := 0.20
const RAIL_HEIGHT := 0.30
const RAIL_LIGHT_HEIGHT := 0.045
const RAIL_LIGHT_INSET := 0.055

# Pillars under a raised deck. The single most effective depth cue in the
# frame after the height hierarchy itself: a deck with air and a shadow
# beneath it is unmistakably an object, where the same deck lying on a floor
# is a marking.
const PILLAR_SPACING := 2.6
const PILLAR_WIDTH := 0.28
const PILLAR_CAP := 0.16
const PILLAR_FOOT := 0.44
const BRACE_WIDTH := 0.13

# --- deck geometry --------------------------------------------------------

# Narrower than a racer is not a channel. Used to reject the slivers a
# conservative wall measurement leaves either side of a joint.
const MIN_SPAN := 60.0
const BRACE_DROP := 2.4
# Samples either side of a cross-section that its edges are averaged over.
# Three is a hair over one wall box at the sampling rate above.
const EDGE_SMOOTHING := 3
# The recessed centre panel: how much of the deck it covers, and how far it
# is let into it.
const PANEL_INSET := 0.62
# Laid on rather than let in: a swept solid cannot cut a recess, and a
# panel a hair proud of the deck reads as an inlay just as well.
const PANEL_SPINE := 0.16
const PANEL_DEPTH := 0.012

# --- the bowl -------------------------------------------------------------

# The vessel wall's thickness at the rim, the air gap out to the acrylic
# shell around it, and how much wider that shell is.
const BOWL_WALL := 0.26
const FLANGE_SINK := 0.05
const BOWL_GLASS_DROP := 0.95
const BOWL_GLASS_SWELL := 1.115
const DRAIN_WELL_DEPTH := 2.60
const BOWL_LEGS := 6

# --- the start platform ---------------------------------------------------

const PLATFORM_OVERHANG := 150.0
const PLATFORM_THICKNESS := 0.52
const PLATFORM_HOUSING := 0.42
const GRID_LANES := 8
const GATE_BLADES := 8
const GATE_HEIGHT := 0.74
const GATE_DEPTH := 0.16
const GATE_GAP := 0.05
const GATE_LIGHT := 0.10
const GATE_HOUSING := 0.34
const SIGN_HEIGHT := 2.55
const SIGN_PANEL := Vector3(0.0, 0.86, 0.22)

# How far a column is pushed into the floor, so a rank of them does not read
# as a row of identical objects standing on nothing.
const COLUMN_SINK := 1.2
# Cross-beams between the far columns: how far apart, and at what heights
# above the machine's own deck.
const GANTRY_SPACING := 1700.0
const GANTRY_HIGH := 6.4
const GANTRY_REACH := 7.0

# --- racers ---------------------------------------------------------------

const BADGE_RISE := 0.42
const BADGE_FONT_SIZE := 120
const BADGE_PIXEL_SIZE := 0.0020
const BADGE_OUTLINE := 26

# --- the shutter ----------------------------------------------------------

# The release, in seconds of replay before the gate is recorded open. The
# leaves finish moving exactly as the simulation removes the floor, so no
# marble is drawn passing through a leaf that is still in the way.
const SHUTTER_SECONDS := 0.28
const SHUTTER_TRAVEL := 1.9

# How near a whole frame the playhead has to be to *be* that frame. Sample
# times are computed by dividing and multiplying and floating point lands
# either side of the integer.
const PLAYHEAD_SNAP := 1.0e-6

# Which lens a race was asked for. The prototype has one, and it is the
# production one: the measuring lens exists to prove that the *production*
# scene draws racers where the replay puts them, and it does that by stripping
# out every piece of presentation until only the geometry is left. There is
# nothing yet to prove about a scene that may be thrown away, and a second
# lens would be a second thing to keep working. So this is recorded and not
# acted on, and a verification render of a neon replay comes back as the
# production picture rather than as a broken one.
var camera_mode := "production"

var _course: Dictionary = {}
var _meta: Dictionary = {}
var _frames: Array = []
var _racer_meta: Array = []

var _course_width := 1080.0
var _course_top := 0.0
var _course_bottom := 4120.0

# The bowl, read from the course rather than assumed.
var _bowl_cx := 540.0
var _bowl_cy := 1820.0
var _bowl_r := 470.0
var _bowl_top := 1350.0
var _drain_half := 110.0
var _drain_y := 1820.0
var _hole_rho := 0.234

var _gate_y := 740.0
var _platform_top := 430.0
var _platform_left := 95.0
var _platform_right := 985.0
var _throat_end := 2200.0
var _bridge_top := 2200.0
var _bridge_end := 3800.0

# Where the shot changes gear, in course pixels. Built once from the machine.
var _phase_release := Vector2.ZERO
var _phase_bowl := Vector2.ZERO
var _phase_bridge := Vector2.ZERO

var _palette: RefCounted
var _camera: Camera3D
var _elevation := CAM_ELEVATION
var _base_distance := 40.0

var _racer_nodes: Array[Node3D] = []
var _racer_spheres: Array[MeshInstance3D] = []
var _racer_radius: Array[float] = []

var _shutter_leaves: Array[Node3D] = []
var _shutter_home: Array[float] = []
var _gate_tick := -1.0

var _physics_hz := 120.0
var _ticks_per_frame := 2.0
var _countries := false


func build(replay: Dictionary, mode := "production") -> void:
	camera_mode = mode
	_course = replay.get("course", {})
	_meta = _course.get("metadata", {})
	_frames = replay.get("frames", [])
	_racer_meta = replay.get("racers", [])
	_course_width = maxf(1.0, float(_course.get("width", 1080.0)))
	_course_top = float(_course.get("top", 0.0))
	_course_bottom = float(_course.get("bottom", 4120.0))
	_physics_hz = maxf(1.0, float(replay.get("physics_hz", 120.0)))
	_ticks_per_frame = maxf(1.0, float(replay.get("ticks_per_frame", 2.0)))
	_countries = _flag("--neon-countries")

	_read_machine()
	_gate_tick = _find_gate_tick()

	_palette = NeonMaterials.new()

	_build_environment()
	_build_lights()
	_build_camera()
	_build_room()
	_build_start_platform()
	_build_deck("chute", true)
	_build_bowl()
	_build_deck("throat", false, false, -8.0)
	_build_deck("bridge", true)
	_build_deck("finish", false)
	_build_racers()


func _read_machine() -> void:
	## Where the machine's parts are, taken from the course and not guessed.
	##
	## The defaults are the neon course's own numbers, so a replay of some
	## other course still renders something rather than collapsing onto zero -
	## but the whole point of the export is that nothing here has to know them.
	_bowl_cx = float(_meta.get("bowl_centre_x", _course_width * 0.5))
	_bowl_cy = float(_meta.get("bowl_centre_y", 1820.0))
	_bowl_r = maxf(1.0, float(_meta.get("bowl_radius", 470.0)))
	_bowl_top = float(_meta.get("bowl_top", _bowl_cy - _bowl_r))
	_drain_half = float(_meta.get("drain_half", 110.0))
	_drain_y = float(_meta.get("drain_y", _bowl_cy))
	_hole_rho = clampf(_drain_half / _bowl_r, 0.02, FLOOR_RHO * 0.95)
	_gate_y = float(_meta.get("gate_y", 740.0))
	_platform_top = float(_meta.get("platform_top", 430.0))
	_platform_left = float(_meta.get("platform_left", 95.0))
	_platform_right = float(_meta.get("platform_right", 985.0))
	_throat_end = float(_meta.get("throat_end", 2200.0))
	_bridge_top = float(_meta.get("bridge_top", _throat_end))
	_bridge_end = float(_meta.get("bridge_end", 3800.0))

	var bowl_in := _bowl_top + PHASE_BOWL_INSET
	var bridge_in := _bridge_top + PHASE_BRIDGE_INSET
	_phase_release = Vector2(_gate_y - PHASE_RELEASE_LEAD, bowl_in)
	_phase_bowl = Vector2(bowl_in, bridge_in)
	_phase_bridge = Vector2(
		bridge_in,
		_bridge_top + (_bridge_end - _bridge_top) * PHASE_BRIDGE_SHARE)


# --- the presentation mapping ---------------------------------------------

func to_world(sim_x: float, sim_y: float, height: float) -> Vector3:
	## Simulation x to world X, simulation y to world Z, Y from the mapping.
	##
	## X is centred on the course so the camera can sit on the middle line;
	## Z is the course height itself, so the exported camera track can be read
	## straight out of the replay with no offset in between.
	return Vector3(
		(sim_x - _course_width * 0.5) / PIXELS_PER_UNIT,
		height + deck_height(sim_x, sim_y),
		sim_y / PIXELS_PER_UNIT)


func to_units(pixels: float) -> float:
	return pixels / PIXELS_PER_UNIT


func bowl_rho(sim_x: float, sim_y: float) -> float:
	## Bowl-local radius: distance from the bowl centre over the bowl radius.
	var dx := sim_x - _bowl_cx
	var dy := sim_y - _bowl_cy
	return sqrt(dx * dx + dy * dy) / _bowl_r


func bowl_profile(rho: float) -> float:
	## How deep the bowl is at a radius, as a fraction of `BOWL_DEPTH`.
	##
	## 1.0 on the flat floor, 0.0 on the lip. The power is above 1.0, which
	## puts the steepest part of the wall at the rim and flattens it towards
	## the drain - a bowl's cross-section rather than a cone's, and the shape
	## that lets a marble arriving fast cross the floor and run up the far
	## side instead of stopping in the middle.
	if rho <= FLOOR_RHO:
		return 1.0
	if rho >= 1.0:
		return 0.0
	var q := (rho - FLOOR_RHO) / (1.0 - FLOOR_RHO)
	return 1.0 - pow(q, BOWL_PROFILE_POWER)


func bowl_surface_y(rho: float) -> float:
	return H_RIM - BOWL_DEPTH * bowl_profile(clampf(rho, 0.0, FLANGE_OUTER))


func deck_height(sim_x: float, sim_y: float) -> float:
	## The one function the whole machine is built from. See the file header.
	if sim_y <= _gate_y:
		return H_START
	if sim_y <= _bowl_top:
		var chute := (sim_y - _gate_y) / maxf(1.0, _bowl_top - _gate_y)
		# Eased at both ends, so the deck leaves the platform level and
		# arrives at the rim level with no crease at either seam.
		return lerpf(H_START, H_RIM, smoothstep(0.0, 1.0, chute))
	if sim_y <= _drain_y:
		return bowl_surface_y(bowl_rho(sim_x, sim_y))
	if sim_y <= _throat_end:
		var throat := (sim_y - _drain_y) / maxf(1.0, _throat_end - _drain_y)
		# Eased away from the bowl's own surface at this point, not from its
		# floor. Near the drain the two are the same thing - inside the flat
		# floor radius the surface *is* the floor - so this is what a racer
		# going down the throat has always seen. Away from the drain they are
		# not: the first version started the throat at the floor height for
		# every x, which left a third of a unit of step across the drain plane
		# anywhere but the middle of it. No racer can reach there, because the
		# throat walls hold them inside the drain, and a mapping with a cliff
		# in it that happens to be unreachable is a trap rather than a
		# decision.
		return lerpf(
			bowl_surface_y(bowl_rho(sim_x, sim_y)),
			H_THROAT,
			smoothstep(0.0, 1.0, throat))
	if sim_y <= _bridge_end:
		var bridge := (sim_y - _throat_end) / maxf(1.0, _bridge_end - _throat_end)
		return lerpf(H_THROAT, H_BRIDGE_END, bridge)
	var tail := clampf(
		(sim_y - _bridge_end) / maxf(1.0, _course_bottom - _bridge_end), 0.0, 1.0)
	return H_BRIDGE_END - H_FINISH_DROP * tail


func _phase(span: Vector2, sim_y: float) -> float:
	return smoothstep(span.x, span.y, sim_y)


func _flag(name: String) -> bool:
	for argument in OS.get_cmdline_user_args():
		var arg: String = argument
		if arg == name:
			return true
		if arg.begins_with(name + "=") and not arg.ends_with("=0"):
			return true
	return false


# --- environment ----------------------------------------------------------

func _build_environment() -> void:
	## A dark chamber with air in it, and a sky that is never drawn.
	##
	## The sky is the most important object in this scene and it is invisible.
	## Nearly every surface in the machine is at least partly metallic, and a
	## metal surface is mostly a mirror: what it shows is whatever the
	## environment gives it to reflect. With no reflection source a light
	## silver deck renders as flat grey paint and a polished rail renders as a
	## black stripe. So there is a sky - cool overhead, warmer at the horizon,
	## near-black underneath - used only as a light and reflection probe, and
	## it is what puts the long soft sheen down every rail and across the bowl.
	var environment := Environment.new()
	environment.background_mode = Environment.BG_COLOR
	environment.background_color = Color(0.012, 0.015, 0.022)

	var sky_material := ProceduralSkyMaterial.new()
	sky_material.sky_top_color = Color(0.105, 0.148, 0.212)
	sky_material.sky_horizon_color = Color(0.170, 0.222, 0.300)
	sky_material.sky_curve = 0.20
	sky_material.ground_horizon_color = Color(0.070, 0.088, 0.122)
	sky_material.ground_bottom_color = Color(0.016, 0.020, 0.028)
	sky_material.ground_curve = 0.10
	# No sun disc: the key light is a light, and a bright disc in the
	# reflection would land as a hot spot where nothing is shining from.
	sky_material.sun_angle_max = 0.0
	sky_material.energy_multiplier = 1.0

	var sky := Sky.new()
	sky.sky_material = sky_material
	sky.radiance_size = Sky.RADIANCE_SIZE_128
	# Fully recomputed rather than reprojected from the previous frame:
	# anything that carried state between draws would make the first frame of
	# a render differ from the same frame rendered later.
	sky.process_mode = Sky.PROCESS_MODE_QUALITY
	environment.sky = sky

	environment.ambient_light_source = Environment.AMBIENT_SOURCE_SKY
	environment.ambient_light_sky_contribution = 1.0
	environment.ambient_light_energy = 0.70
	environment.reflected_light_source = Environment.REFLECTION_SOURCE_SKY

	environment.tonemap_mode = Environment.TONE_MAPPER_ACES
	environment.tonemap_white = 2.4
	environment.tonemap_exposure = 1.0

	# Depth fog, tuned to where this machine actually sits. The lens is about
	# thirty units from what it is looking at, so a fog that began at twenty -
	# right for the race scene's much closer framing - would haze over the
	# subject. It begins just behind the aim and closes over the far columns.
	environment.fog_enabled = true
	environment.fog_mode = Environment.FOG_MODE_DEPTH
	environment.fog_light_color = Color(0.048, 0.072, 0.112)
	environment.fog_light_energy = 1.0
	environment.fog_depth_begin = 34.0
	environment.fog_depth_end = 108.0
	environment.fog_depth_curve = 1.5
	environment.fog_sky_affect = 0.0

	# Glow on a short leash, and the picture is built not to need it. The
	# threshold sits above every lit surface on the machine except the start
	# treatment and the drain collar, so those two bloom and nothing else
	# does. Turn it loose and a machine made of pale decks hazes over into one
	# bright shape.
	environment.glow_enabled = true
	environment.glow_intensity = 0.42
	environment.glow_strength = 1.0
	environment.glow_bloom = 0.0
	environment.glow_blend_mode = Environment.GLOW_BLEND_MODE_ADDITIVE
	environment.glow_hdr_threshold = 1.05
	environment.glow_hdr_scale = 2.0
	environment.set_glow_level(1, 0.0)
	environment.set_glow_level(2, 0.5)
	environment.set_glow_level(3, 1.0)
	environment.set_glow_level(4, 0.6)
	environment.set_glow_level(5, 0.2)
	environment.set_glow_level(6, 0.0)

	# Contact darkening where geometry meets geometry. This is what seats a
	# marble on the bowl and a pillar on the floor, and on a machine this pale
	# it does more work than it does on a dark one.
	environment.ssao_enabled = true
	environment.ssao_radius = 0.70
	environment.ssao_intensity = 2.1
	environment.ssao_power = 1.6
	environment.ssao_detail = 0.5
	environment.ssao_light_affect = 0.10

	var world := WorldEnvironment.new()
	world.name = "WorldEnvironment"
	world.environment = environment
	add_child(world)


func _build_lights() -> void:
	## A key across the machine, a cool fill, and a kicker along the lens.
	##
	## The key is angled across the course rather than down it, and that is
	## the whole reason this machine has shape. A light straight overhead puts
	## every shadow underneath the thing casting it: the bridge would have no
	## visible underside, the pillars would have no length and the bowl would
	## have no terminator across its curve. Across the course, every beam gets
	## a lit face and a dark face, every pillar throws a shadow onto the floor
	## far below, and the bowl goes light on one side and dark on the other -
	## which is what reads as depth.
	var key := DirectionalLight3D.new()
	key.name = "KeyLight"
	key.light_color = Color(1.0, 0.972, 0.930)
	key.light_energy = 1.65
	key.light_specular = 1.0
	key.shadow_enabled = true
	key.directional_shadow_mode = DirectionalLight3D.SHADOW_PARALLEL_4_SPLITS
	# The machine is 41 units long and the frame shows about 27 of them, and
	# the pillars drop twelve units to a floor that also has to receive
	# shadow, so the range covers rather more than the visible track.
	key.directional_shadow_max_distance = 96.0
	key.directional_shadow_split_1 = 0.10
	key.directional_shadow_split_2 = 0.24
	key.directional_shadow_split_3 = 0.52
	key.directional_shadow_blend_splits = true
	key.shadow_bias = 0.028
	key.shadow_normal_bias = 1.1
	key.shadow_opacity = 0.92
	key.rotation_degrees = Vector3(-46.0, 36.0, 0.0)
	add_child(key)

	var fill := DirectionalLight3D.new()
	fill.name = "FillLight"
	fill.light_color = Color(0.40, 0.60, 1.0)
	fill.light_energy = 0.80
	fill.light_specular = 0.30
	fill.shadow_enabled = false
	fill.rotation_degrees = Vector3(-22.0, -134.0, 0.0)
	add_child(fill)

	# A cold light almost along the camera axis, low and behind, purely to put
	# a bright edge on the far side of every marble. It is what stops sixteen
	# glossy spheres merging into one shape in the bowl.
	var kicker := DirectionalLight3D.new()
	kicker.name = "KickerLight"
	kicker.light_color = Color(0.58, 0.86, 1.0)
	kicker.light_energy = 0.80
	kicker.light_specular = 1.5
	kicker.shadow_enabled = false
	kicker.rotation_degrees = Vector3(-14.0, 184.0, 0.0)
	add_child(kicker)


# --- camera ---------------------------------------------------------------

func _build_camera() -> void:
	## Elevated perspective, framed so the course cannot run out sideways.
	##
	## The distance is derived rather than dialled in: the course is fitted
	## across the point the lens is aimed at, so
	##
	##     half_wide = D tan(h) = half the course + a margin
	##
	## The race scene fits the course at the *near* edge of the frustum
	## instead, where a tilted lens is narrowest against the ground. That is
	## the right rule for a course that is full width from end to end, and the
	## wrong one here: it puts the lens forty units out to protect ground the
	## machine does not stand on, and the machine then occupies a third of the
	## frame with the rest given over to the room. Fitting at the aim brings
	## it to twenty-eight, and the widest thing on the machine - the bowl's
	## lip, at 10.9 units - still crosses the frame with room to spare.
	_camera = Camera3D.new()
	_camera.name = "Camera3D"
	_camera.projection = Camera3D.PROJECTION_PERSPECTIVE
	_camera.keep_aspect = Camera3D.KEEP_HEIGHT
	_camera.fov = CAM_FOV
	_camera.near = 0.20
	_camera.far = 320.0
	_elevation = _elevation_argument()

	var viewport_width := float(ProjectSettings.get_setting(
		"display/window/size/viewport_width", 1080))
	var viewport_height := float(ProjectSettings.get_setting(
		"display/window/size/viewport_height", 1920))
	var half_v := deg_to_rad(CAM_FOV * 0.5)
	var half_h := atan(tan(half_v) * viewport_width / viewport_height)

	var needed := to_units(_course_width) * 0.5 + CAM_EDGE_MARGIN
	_base_distance = needed / maxf(0.02, tan(half_h))
	add_child(_camera)


func _elevation_argument() -> float:
	## `--race-elevation=52` shoots this render at fifty-two degrees.
	##
	## A render-time override rather than an edit to the constant, because the
	## point of the sweep is that the candidate frames come out of one build
	## of one scene from one replay - anything else and what is being compared
	## is not only the lens. The argument name is shared with the race scene
	## deliberately: one project, one way to ask for an elevation.
	for argument in OS.get_cmdline_user_args():
		var arg: String = argument
		if arg.begins_with("--race-elevation="):
			var value := arg.substr(17).to_float()
			if value >= 20.0 and value <= 89.0:
				return value
	return CAM_ELEVATION


func _update_camera(frame: Dictionary, next_frame: Dictionary, blend: float) -> void:
	## One flowing shot, computed from the frame in front of it.
	##
	## Wide on the platform, in and down as the field reaches the bowl, out
	## and along as it reaches the bridge, with a slow orbit under the whole
	## thing. Every term is a smoothstep of the aim's course height, so there
	## is nothing to accumulate and no cut anywhere in it.
	var top := lerpf(
		float(frame.get("camera_y", 0.0)),
		float(next_frame.get("camera_y", 0.0)),
		blend)
	var aim_y := top + CAM_LEAD

	var wide := 1.0 - _phase(_phase_release, aim_y)
	var bowl := _phase(_phase_bowl, aim_y)
	var bridge := _phase(_phase_bridge, aim_y)
	aim_y += LEAD_BRIDGE * bridge

	var dolly := 1.0 + DOLLY_WIDE * wide - DOLLY_BOWL * bowl + DOLLY_BRIDGE * bridge
	var elevation := deg_to_rad(_elevation - DIP_BOWL * bowl + DIP_BRIDGE * bridge)
	var distance := _base_distance * dolly

	var aim := Vector3(
		0.0,
		deck_height(_bowl_cx, aim_y) + CAM_AIM_LIFT - LIFT_BOWL * bowl,
		to_units(aim_y))

	var offset := Vector3(
		0.0, distance * sin(elevation), -distance * cos(elevation))
	var orbit := deg_to_rad(lerpf(
		ORBIT_FROM, ORBIT_TO, smoothstep(ORBIT_SPAN.x, ORBIT_SPAN.y, aim_y)))
	offset = offset.rotated(Vector3.UP, orbit)

	_camera.position = aim + offset
	_camera.look_at(aim, Vector3.UP)


func _find_gate_tick() -> float:
	## The tick the simulation removed the floor on, read from the frames.
	##
	## The shutter is animated to *finish* here rather than start here, so no
	## marble is ever drawn passing through a leaf that has not moved yet.
	for frame in _frames:
		var entry: Dictionary = frame
		if bool(entry.get("gates_open", false)):
			return float(entry.get("tick", 0))
	return -1.0


# --- mesh primitives ------------------------------------------------------
#
# Godot's front faces are wound so that the cross product `(b - a) x (c - a)`
# points *away* from the surface normal - that is what `Plane(p1, p2, p3)`
# computes, and the engine's own normal generation is built on it. Everything
# below orders its vertices to satisfy that, and passes the normal explicitly
# rather than relying on generation, because a deck and its own underside
# want opposite normals out of the same four corners.

func _quad(surface: SurfaceTool, a: Vector3, b: Vector3, c: Vector3,
		d: Vector3, normal: Vector3) -> void:
	for vertex in [a, b, c, a, c, d]:
		surface.set_normal(normal)
		surface.add_vertex(vertex)


func _quad_smooth(surface: SurfaceTool, points: Array, normals: Array) -> void:
	## The same quad with a normal per corner, for a curved surface.
	for index in [0, 1, 2, 0, 2, 3]:
		surface.set_normal(normals[index])
		surface.add_vertex(points[index])


func _mesh_node(node_name: String, mesh: ArrayMesh, materials: Array,
		shadows := true) -> MeshInstance3D:
	var node := MeshInstance3D.new()
	node.name = node_name
	node.mesh = mesh
	for index in mini(materials.size(), mesh.get_surface_count()):
		mesh.surface_set_material(index, materials[index])
	if not shadows:
		node.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
	return node


func _box(node_name: String, size: Vector3, position: Vector3,
		material: StandardMaterial3D, shadows := true) -> MeshInstance3D:
	var mesh := BoxMesh.new()
	mesh.size = size
	var node := MeshInstance3D.new()
	node.name = node_name
	node.mesh = mesh
	node.material_override = material
	node.position = position
	if not shadows:
		node.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
	return node


# --- decks ----------------------------------------------------------------
#
# A deck is a solid ribbon following the channel the simulation's walls make,
# and it is derived from those walls rather than described anywhere. That is
# what lets one builder produce the chute's twin spouts, the throat, the
# S-curve bridge and the finish apron: it samples the course every
# `DECK_STEP` pixels, asks what is clear at that height, and sweeps a solid
# through the answer.
#
# A cross-section is carried as a Vector3 of (left edge, right edge, course
# height), all in simulation pixels. Three numbers is what a swept solid
# needs and a dictionary per sample would be a few thousand allocations.

func _piece_span(spec: Dictionary, y: float) -> Vector2:
	## What a piece blocks on the x axis at a course height, or a zero span.
	##
	## Conservative: a rotated box is measured by its axis-aligned extent, so
	## a steeply angled wall claims slightly more of the axis than it really
	## occupies. That is the right way round - a deck that stops a little
	## short of a wall is covered by the rail standing on it, and a deck that
	## overshoots pokes out through the wall.
	var piece_y := float(spec.get("y", 0.0))
	if str(spec.get("type", "")) == "circle":
		var radius := float(spec.get("radius", 0.0))
		if absf(y - piece_y) > radius:
			return Vector2.ZERO
		# The chord rather than the diameter: a peg caught at the edge of a
		# sample blocks almost nothing there.
		var half := sqrt(maxf(1.0, radius * radius - pow(y - piece_y, 2.0)))
		var centre := float(spec.get("x", 0.0))
		return Vector2(centre - half, centre + half)

	var half_w := float(spec.get("width", 0.0)) * 0.5
	var half_h := float(spec.get("height", 0.0)) * 0.5
	var angle := deg_to_rad(float(spec.get("rotation_degrees", 0.0)))
	# A near-horizontal piece is a floor, not the wall of a channel. Skipping
	# them is what stops the finish apron's own floor being read as a wall
	# right across the section it is the floor of.
	if absf(sin(angle)) < 0.25:
		return Vector2.ZERO

	# Where the plane actually cuts the box, found by clipping its outline
	# against the line - not the box's axis-aligned extent.
	#
	# The extent was the first version and it is wrong in one specific way
	# that matters: it is the same at every height, so a wall that *leans*
	# claims the same slice of the x axis all the way down itself. The finish
	# apron is one long ramp per side flaring from 300 pixels wide to 810, and
	# it came out as a deck of one constant width with the rails standing up
	# in the middle of the basin and six marbles ending the race in the void
	# beside them. A leaning wall is at a different x at every y, and the deck
	# under it has to be too.
	var cos_a := cos(angle)
	var sin_a := sin(angle)
	var piece_x := float(spec.get("x", 0.0))
	var corners: Array[Vector2] = []
	for signs in [Vector2(-1.0, -1.0), Vector2(1.0, -1.0),
			Vector2(1.0, 1.0), Vector2(-1.0, 1.0)]:
		corners.append(Vector2(
			piece_x + signs.x * half_w * cos_a - signs.y * half_h * sin_a,
			piece_y + signs.x * half_w * sin_a + signs.y * half_h * cos_a))

	var lowest := INF
	var highest := -INF
	for index in 4:
		var here: Vector2 = corners[index]
		var next: Vector2 = corners[(index + 1) % 4]
		if absf(here.y - y) < 1.0e-6:
			lowest = minf(lowest, here.x)
			highest = maxf(highest, here.x)
		if (here.y - y) * (next.y - y) >= 0.0 or here.y == next.y:
			continue
		var t := (y - here.y) / (next.y - here.y)
		var crossing := here.x + t * (next.x - here.x)
		lowest = minf(lowest, crossing)
		highest = maxf(highest, crossing)
	if lowest > highest:
		return Vector2.ZERO
	return Vector2(lowest, highest)


func _clear_spans(section: String, y: float) -> Array:
	## Every gap in one section's walls at a course height, left to right.
	var blocked: Array = []
	for raw in _course.get("pieces", []):
		var spec: Dictionary = raw
		if str(spec.get("section", "")) != section:
			continue
		if str(spec.get("role", "")) == "gate":
			continue
		var span := _piece_span(spec, y)
		if span != Vector2.ZERO:
			blocked.append(span)
	blocked.sort_custom(func(a, b): return a.x < b.x)

	# Only gaps walled on *both* sides count. Anything running off to a course
	# edge is not a channel - it is the open air beside the machine, and the
	# first version of this happily paved it: the chute came out ten units
	# wide with the spouts drawn as scratches on it.
	var spans: Array = []
	if blocked.size() < 2:
		return spans
	var cursor: float = (blocked[0] as Vector2).y
	for index in range(1, blocked.size()):
		var span: Vector2 = blocked[index]
		if span.x - cursor > MIN_SPAN:
			spans.append(Vector2(cursor, span.x))
		cursor = maxf(cursor, span.y)
	return spans


func _section_bounds(section: String) -> Vector2:
	for raw in _course.get("sections", []):
		var entry: Dictionary = raw
		if str(entry.get("name", "")) == section:
			return Vector2(
				float(entry.get("top", 0.0)), float(entry.get("bottom", 0.0)))
	return Vector2.ZERO


func _deck_ribbons(section: String) -> Array:
	## The channels through one section, as lists of cross-sections.
	##
	## Sampled top to bottom. While the number of gaps holds steady each
	## sample is appended to the run it continues; when the count changes -
	## the chute's single mouth becoming two spouts either side of the wedge -
	## the open runs are closed and new ones begun *on the same plane*, so the
	## two sweeps meet rather than leaving a step of deck unswept between
	## them. On this machine the count changes in exactly one place, under the
	## wedge's dome, and the deck steps from one channel to two there.
	var bounds := _section_bounds(section)
	if bounds == Vector2.ZERO:
		return []
	var start := bounds.x
	var finish := bounds.y - 2.0
	if finish <= start:
		return []
	var steps := maxi(1, int((finish - start) / DECK_STEP))

	var ribbons: Array = []
	var open: Array = []
	var previous := start
	for step in steps + 1:
		var y := start + float(step) * (finish - start) / float(steps)
		var spans := _clear_spans(section, y)
		if spans.size() != open.size():
			# The runs that end and the runs that begin have to meet on one
			# plane, and it is the midpoint of the step the count changed
			# across. Closing at the last sample and opening at the next one
			# leaves a full sample step of nothing swept - and because every
			# run is capped at both ends, that is an open slot right across
			# the deck rather than a seam. On the chute it fell exactly where
			# the wedge's dome first appears, and the whole field of sixteen
			# was drawn crossing it.
			#
			# Abutting is safe where overlapping would not be: the closing
			# run's end cap and the opening run's start cap are coplanar with
			# opposite normals, so whichever one faces the lens is the only
			# one drawn.
			var seam := (previous + y) * 0.5
			var seamed := seam > previous + 0.5
			for raw_run in open:
				var run: Array = raw_run
				if seamed and not run.is_empty():
					var last: Vector3 = run[run.size() - 1]
					run.append(Vector3(last.x, last.y, seam))
				if run.size() >= 2:
					ribbons.append(run)
			open = []
			for index in spans.size():
				var opening: Vector2 = spans[index]
				open.append(
					[Vector3(opening.x, opening.y, seam)] if seamed else [])
		for index in spans.size():
			var span: Vector2 = spans[index]
			(open[index] as Array).append(Vector3(span.x, span.y, y))
		previous = y
	for run in open:
		if (run as Array).size() >= 2:
			ribbons.append(run)

	# A wall's first box only just reaches the plane its section begins at, so
	# the top sample can fall on either side of it depending on rounding. The
	# first run is pulled back to the section top rather than left to chance,
	# because the gap that leaves is the seam between two stretches of track.
	if not ribbons.is_empty():
		var first: Array = ribbons[0]
		var head: Vector3 = first[0]
		if head.z > start + 1.0:
			first.insert(0, Vector3(head.x, head.y, start))

	var smoothed: Array = []
	for run in ribbons:
		smoothed.append(_smooth(run))
	return smoothed


func _smooth(samples: Array) -> Array:
	"""Round the scallop out of a swept edge.

	A wall is a chain of straight boxes that overlap at every joint, and where
	two overlap the clear width is decided by whichever of them claims more of
	the x axis - so a curved wall's inner face has a shallow corner at each
	joint rather than a continuous curve. Averaging over a window a little
	wider than one box removes them and leaves the curve itself, which is two
	orders of magnitude longer, untouched.

	It moves the drawn edge by a few pixels and nothing else. The racing line
	is the simulation's, and the deck already reaches past the wall by a
	rail's width, so a smoothed edge is still under every racer.
	"""
	if samples.size() < 3:
		return samples
	var out: Array = []
	for index in samples.size():
		var left := 0.0
		var right := 0.0
		var count := 0
		for offset in range(-EDGE_SMOOTHING, EDGE_SMOOTHING + 1):
			var at := clampi(index + offset, 0, samples.size() - 1)
			var sample: Vector3 = samples[at]
			left += sample.x
			right += sample.y
			count += 1
		var here: Vector3 = samples[index]
		out.append(Vector3(left / float(count), right / float(count), here.z))
	return out


func _solid_ribbon(node_name: String, samples: Array, rise: float,
		thickness: float, materials: Array, shadows := true) -> MeshInstance3D:
	## One swept solid: a top face, two sides, an underside and two ends.
	##
	## Three surfaces rather than one material, because the whole reason a
	## beam reads as a beam is that its top is pale and its sides and its
	## underside are not. `rise` lifts the top face above the deck line, which
	## is how the same sweep produces the deck, the rails standing on it and
	## the lit strip let into each rail.
	var top := SurfaceTool.new()
	var side := SurfaceTool.new()
	var under := SurfaceTool.new()
	for surface in [top, side, under]:
		surface.begin(Mesh.PRIMITIVE_TRIANGLES)

	var drop := Vector3(0.0, -thickness, 0.0)
	for index in samples.size() - 1:
		var here := _ribbon_edges(samples[index], rise)
		var next := _ribbon_edges(samples[index + 1], rise)
		var l0: Vector3 = here[0]
		var r0: Vector3 = here[1]
		var l1: Vector3 = next[0]
		var r1: Vector3 = next[1]

		_quad(top, l0, r0, r1, l1, Vector3.UP)
		_quad(under, l0 + drop, l1 + drop, r1 + drop, r0 + drop, Vector3.DOWN)
		_quad(side, r0, r0 + drop, r1 + drop, r1, Vector3.RIGHT)
		_quad(side, l0, l1, l1 + drop, l0 + drop, Vector3.LEFT)

	var first := _ribbon_edges(samples[0], rise)
	_quad(side, first[0], first[0] + drop, first[1] + drop, first[1],
		Vector3.FORWARD)
	var last := _ribbon_edges(samples[samples.size() - 1], rise)
	_quad(side, last[0], last[1], last[1] + drop, last[0] + drop, Vector3.BACK)

	var mesh := ArrayMesh.new()
	top.commit(mesh)
	side.commit(mesh)
	under.commit(mesh)
	return _mesh_node(node_name, mesh, materials, shadows)


func _ribbon_edges(sample: Vector3, rise: float) -> Array:
	## One cross-section as its two world-space top corners.
	##
	## The height is taken on the cross-section's centre line. Outside the
	## bowl the mapping does not depend on x at all, and no deck is ever built
	## inside the bowl - the bowl mesh is - so that is the whole answer rather
	## than an approximation of one.
	var height := deck_height((sample.x + sample.y) * 0.5, sample.z) + rise
	var z := to_units(sample.z)
	return [
		Vector3(to_units(sample.x - _course_width * 0.5), height, z),
		Vector3(to_units(sample.y - _course_width * 0.5), height, z),
	]


func _inset(samples: Array, fraction: float) -> Array:
	## The middle share of a run, as a fraction of its own width.
	var moved: Array = []
	for raw in samples:
		var sample: Vector3 = raw
		var centre := (sample.x + sample.y) * 0.5
		var half := (sample.y - sample.x) * 0.5 * fraction
		moved.append(Vector3(centre - half, centre + half, sample.z))
	return moved


func _widen(samples: Array, left: float, right: float) -> Array:
	## The same run of cross-sections with its edges moved, in course pixels.
	var moved: Array = []
	for raw in samples:
		var sample: Vector3 = raw
		moved.append(Vector3(sample.x + left, sample.y + right, sample.z))
	return moved


func _band(samples: Array, side: float, inner: float, outer: float) -> Array:
	## A narrow run along one edge of a deck, measured from that edge inwards.
	##
	## `side` is -1 for the left edge and +1 for the right. Both offsets are
	## course pixels from the edge, positive inwards, which is what lets a
	## rail and the strip let into its top be described the same way.
	var moved: Array = []
	for raw in samples:
		var sample: Vector3 = raw
		var edge := sample.x if side < 0.0 else sample.y
		var a := edge + side * -outer
		var b := edge + side * -inner
		moved.append(Vector3(minf(a, b), maxf(a, b), sample.z))
	return moved


func _build_deck(section: String, pillars: bool, rails := true,
		margin := DECK_MARGIN) -> void:
	## One named stretch of track: deck, rails, lit edges and supports.
	##
	## `margin` is how far past the walls the deck reaches, and the throat
	## passes a negative one. It has to: the drain is a hole cut in the bowl
	## at exactly the radius of the throat's walls, so a throat that reached
	## past them would meet the bowl's floor at its own height and fight it
	## for the depth buffer all the way round the opening.
	var ribbons := _deck_ribbons(section)
	if ribbons.is_empty():
		return

	var root := Node3D.new()
	root.name = "Deck_%s" % section
	add_child(root)

	var deck_materials := [
		_palette.track_top(), _palette.track_side(), _palette.track_web()]
	var rail_materials := [
		_palette.rail(), _palette.rail(), _palette.track_web()]
	var light_materials := [
		_palette.edge_light(), _palette.edge_light(), _palette.edge_light()]

	var rail_px := RAIL_WIDTH * PIXELS_PER_UNIT
	var light_px := RAIL_LIGHT_INSET * PIXELS_PER_UNIT

	for index in ribbons.size():
		var raw: Array = ribbons[index]
		# The deck reaches past the walls by exactly a rail's width, so the
		# rails have something to stand on and the racing surface still ends
		# where the simulation says it does.
		var deck := _widen(raw, -margin, margin)
		root.add_child(_solid_ribbon(
			"Surface%d" % index, deck, 0.0, DECK_THICKNESS, deck_materials))

		# A polished rail is the one near-mirror surface on the track. The
		# highlight running along it is most of how a viewer reads an S-bend
		# as a bend rather than as a shape.
		for side in ([-1.0, 1.0] if rails else []):
			var tag := "L" if side < 0.0 else "R"
			root.add_child(_solid_ribbon(
				"Rail%s%d" % [tag, index], _band(deck, side, 0.0, rail_px),
				RAIL_HEIGHT, RAIL_HEIGHT + 0.06, rail_materials))
			root.add_child(_solid_ribbon(
				"Edge%s%d" % [tag, index],
				_band(deck, side, light_px, rail_px - light_px),
				RAIL_HEIGHT + RAIL_LIGHT_HEIGHT, RAIL_LIGHT_HEIGHT,
				light_materials, false))

		# A recessed centre panel. Two values across a deck rather than one is
		# what stops a wide pale surface reading as a sheet of paper, and it
		# runs *along* the direction of travel - a line drawn across a deck
		# reads as a rung and puts the frame back into diagram territory.
		root.add_child(_solid_ribbon("Panel%d" % index,
			_inset(deck, PANEL_INSET), PANEL_DEPTH, DECK_THICKNESS * 0.5,
			[_palette.track_top(true), _palette.track_side(),
				_palette.track_web()], false))
		root.add_child(_solid_ribbon("Spine%d" % index,
			_inset(deck, PANEL_SPINE), PANEL_DEPTH * 2.0, DECK_THICKNESS * 0.5,
			[_palette.track_side(), _palette.track_side(),
				_palette.track_web()], false))

		if pillars:
			_build_pillars(root, deck, index)


func _build_pillars(root: Node3D, samples: Array, ribbon: int) -> void:
	## Posts from the underside of a deck down to the floor of the room.
	##
	## The brief calls the empty space under the bridge essential and it is
	## right: a deck with air and a shadow beneath it is unmistakably an
	## object, where the same deck lying on a floor is a marking. The posts
	## are what make that space readable - without something crossing it,
	## twelve units of darkness is only darkness.
	var span := float((samples[samples.size() - 1] as Vector3).z) \
		- float((samples[0] as Vector3).z)
	var count := maxi(1, int(to_units(span) / PILLAR_SPACING))
	var previous := Vector3.ZERO

	for index in count:
		var t := (float(index) + 0.5) / float(count)
		var at := int(round(t * float(samples.size() - 1)))
		var sample: Vector3 = samples[clampi(at, 0, samples.size() - 1)]
		var centre := (sample.x + sample.y) * 0.5
		var top := deck_height(centre, sample.z) - DECK_THICKNESS
		var x := to_units(centre - _course_width * 0.5)
		var z := to_units(sample.z)
		var length := top - VOID_FLOOR_Y

		# A cap where the post meets the deck, so the join is a joint rather
		# than a box ending in mid-air.
		root.add_child(_box("Cap%d_%d" % [ribbon, index],
			Vector3(PILLAR_WIDTH * 2.2, PILLAR_CAP, PILLAR_WIDTH * 2.2),
			Vector3(x, top - PILLAR_CAP * 0.5, z),
			_palette.structure(false, true)))
		root.add_child(_box("Pillar%d_%d" % [ribbon, index],
			Vector3(PILLAR_WIDTH, length, PILLAR_WIDTH),
			Vector3(x, top - length * 0.5, z),
			_palette.structure()))
		root.add_child(_box("Foot%d_%d" % [ribbon, index],
			Vector3(PILLAR_FOOT, 0.24, PILLAR_FOOT),
			Vector3(x, VOID_FLOOR_Y + 0.12, z),
			_palette.structure(false, true)))

		# One brace between neighbouring posts, well under the deck so it can
		# never cross a racer, and horizontal so it reads as a frame.
		if index > 0:
			var here := Vector3(x, top, z)
			var delta := here - previous
			var flat := Vector2(delta.x, delta.z).length()
			var brace := _box("Brace%d_%d" % [ribbon, index],
				Vector3(flat, BRACE_WIDTH, BRACE_WIDTH),
				Vector3((previous.x + x) * 0.5,
					(previous.y + top) * 0.5 - BRACE_DROP,
					(previous.z + z) * 0.5),
				_palette.structure(false, true))
			brace.rotation.y = -atan2(delta.z, delta.x)
			root.add_child(brace)
		previous = Vector3(x, top, z)


# --- the bowl -------------------------------------------------------------

func _bowl_centre() -> Vector3:
	## The bowl's centre in world space, at the height of its floor.
	return Vector3(
		to_units(_bowl_cx - _course_width * 0.5),
		bowl_surface_y(0.0),
		to_units(_bowl_cy))


func _bowl_point(rho: float, angle: float, drop: float, swell := 1.0) -> Vector3:
	## A point on the vessel, with the lip bevelled away from the racing line.
	##
	## The bevel is mesh-only and tiny, and it exists to keep two flat
	## surfaces at the same height out of each other's way: the chute's spouts
	## end *on* the lip, and two coplanar decks fight for the depth buffer in
	## a band right where the field pours into the bowl. Dropping the lip five
	## hundredths of a unit across its width settles it, and leaves a racer
	## clamped onto the lip that much above it - five simulation pixels, which
	## is a twentieth of a marble.
	var centre := _bowl_centre()
	var radius := rho * _bowl_r / PIXELS_PER_UNIT * swell
	var bevel := FLANGE_SINK * clampf(
		(rho - 1.0) / maxf(0.01, FLANGE_OUTER - 1.0), 0.0, 1.0)
	return Vector3(
		centre.x + radius * cos(angle),
		bowl_surface_y(rho) - drop - bevel,
		centre.z + radius * sin(angle))


func _bowl_normal(rho: float, angle: float) -> Vector3:
	## The inner surface's normal at a radius, from the slope of the profile.
	##
	## Taken by difference rather than by differentiating `bowl_profile` by
	## hand, so the normals cannot drift away from the surface if the profile
	## is ever reshaped - and the surface is what the racers are placed on.
	var step := 0.004
	var rise := bowl_surface_y(rho + step) - bowl_surface_y(rho - step)
	var run := 2.0 * step * _bowl_r / PIXELS_PER_UNIT
	var slope := rise / maxf(run, 1.0e-6)
	return Vector3(-slope * cos(angle), 1.0, -slope * sin(angle)).normalized()


func _bowl_revolution(inner: float, outer: float, rings: int, segments: int,
		drop: float, swell: float, upward: bool) -> ArrayMesh:
	## A surface of revolution built from the same height function the racers
	## are placed by.
	##
	## This is the load-bearing sentence of the whole prototype. A racer's
	## world Y is `bowl_surface_y(rho) + its radius`, and every vertex of this
	## mesh is `bowl_surface_y(rho)` at that vertex's own radius - so a marble
	## rests exactly on the surface at every point of it, by construction and
	## not by tuning. It cannot sink into the bowl and it cannot hover over
	## it, whatever the physics underneath does.
	var surface := SurfaceTool.new()
	surface.begin(Mesh.PRIMITIVE_TRIANGLES)

	for ring in rings:
		var rho_a := lerpf(inner, outer, float(ring) / float(rings))
		var rho_b := lerpf(inner, outer, float(ring + 1) / float(rings))
		for segment in segments:
			var angle_a := TAU * float(segment) / float(segments)
			var angle_b := TAU * float(segment + 1) / float(segments)
			var points := [
				_bowl_point(rho_a, angle_a, drop, swell),
				_bowl_point(rho_b, angle_a, drop, swell),
				_bowl_point(rho_b, angle_b, drop, swell),
				_bowl_point(rho_a, angle_b, drop, swell),
			]
			var normals := [
				_bowl_normal(rho_a, angle_a),
				_bowl_normal(rho_b, angle_a),
				_bowl_normal(rho_b, angle_b),
				_bowl_normal(rho_a, angle_b),
			]
			if upward:
				_quad_smooth(surface, points, normals)
			else:
				# The underside: the same ring wound the other way round, with
				# the normals turned over.
				_quad_smooth(surface,
					[points[0], points[3], points[2], points[1]],
					[-normals[0], -normals[3], -normals[2], -normals[1]])

	var mesh := ArrayMesh.new()
	surface.commit(mesh)
	return mesh


func _ring(node_name: String, rho: float, thickness: float, height: float,
		drop: float, material: StandardMaterial3D,
		shadows := true) -> MeshInstance3D:
	var mesh := TorusMesh.new()
	var radius := rho * _bowl_r / PIXELS_PER_UNIT
	mesh.inner_radius = maxf(0.02, radius - thickness)
	mesh.outer_radius = radius + thickness
	mesh.rings = 72
	mesh.ring_segments = 12
	var node := MeshInstance3D.new()
	node.name = node_name
	node.mesh = mesh
	node.material_override = material
	var centre := _bowl_centre()
	node.position = Vector3(centre.x, height - drop, centre.z)
	node.scale = Vector3(1.0, 0.55, 1.0)
	if not shadows:
		node.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
	return node


func _build_bowl() -> void:
	## The hero object: a real vessel, not a pair of ramps.
	##
	## Six parts, and each one is answering a line of the brief.
	##
	## The **inner surface** is the racing surface and the thing the mapping
	## is built on. Opaque, so a marble on it has a contact shadow and the
	## curve has a terminator across it - the two cues that say "curved solid"
	## rather than "shape on a floor".
	##
	## The **underside** gives the vessel wall a thickness at the rim, which
	## is where a viewer looks to decide whether a bowl is an object.
	##
	## The **acrylic shell** is a second, larger vessel around the first with
	## an air gap between them. Putting the glass outside the racing surface
	## rather than making the racing surface glass is what buys the acrylic
	## look without costing readability.
	##
	## The **lip**, the **accent ring** and the **drain collar** are the only
	## lit parts, and only the collar is bright enough to bloom - the exit has
	## to read as a hole in the middle of a pale bowl.
	##
	## The **cradle** is the metallic support underneath, and the reason the
	## bowl looks supported rather than placed.
	var root := Node3D.new()
	root.name = "Bowl"
	add_child(root)

	var inner := _mesh_node("Surface",
		_bowl_revolution(_hole_rho, 1.0, 44, 128, 0.0, 1.0, true),
		[_palette.bowl_surface()])
	root.add_child(inner)

	# The lip is drawn as its own part in its own value. A dish and a flange
	# in one tone read as a satellite dish; two tones read as a vessel seated
	# in a machined rim, which is what the reference is.
	var flange := _mesh_node("Flange",
		_bowl_revolution(1.0, FLANGE_OUTER, 8, 128, 0.0, 1.0, true),
		[_palette.track_top(true)])
	root.add_child(flange)

	var under := _mesh_node("Underside",
		_bowl_revolution(_hole_rho, FLANGE_OUTER, 32, 128, BOWL_WALL, 1.0, false),
		[_palette.bowl_shell()])
	root.add_child(under)

	var shell := _mesh_node("Acrylic",
		_bowl_revolution(FLOOR_RHO * 0.8, FLANGE_OUTER * 0.995, 20, 72,
			BOWL_GLASS_DROP, BOWL_GLASS_SWELL, false),
		[_palette.bowl_glass()], false)
	root.add_child(shell)

	# The lip, the ring let into the flange, and the collar round the drain.
	root.add_child(_ring("Lip", FLANGE_OUTER, 0.075, H_RIM - 0.03, 0.0,
		_palette.bowl_shell()))
	root.add_child(_ring("Accent", FLANGE_OUTER * 0.90, 0.038, H_RIM + 0.012,
		0.0, _palette.bowl_accent(), false))
	root.add_child(_ring("Collar", _hole_rho, 0.055,
		bowl_surface_y(0.0) + 0.02, 0.0, _palette.drain_collar(), false))

	# Two machined seams across the dish. Restrained on purpose: a bowl with
	# no surface incident at all renders as one enormous smooth gradient, and
	# a gradient is the one thing that does not read as a manufactured object.
	for raw_seam in [0.52, 0.78]:
		var seam := float(raw_seam)
		root.add_child(_ring("Seam%d" % int(seam * 100.0), seam, 0.016,
			bowl_surface_y(seam) + 0.004, 0.0, _palette.bowl_shell(), false))

	_build_drain_well(root)
	_build_bowl_cradle(root)
	_build_bowl_lights(root)


func _build_drain_well(root: Node3D) -> void:
	## Darker depth below the opening, so the exit is a hole rather than a gap.
	var mesh := CylinderMesh.new()
	mesh.top_radius = _hole_rho * _bowl_r / PIXELS_PER_UNIT
	mesh.bottom_radius = mesh.top_radius * 0.82
	mesh.height = DRAIN_WELL_DEPTH
	mesh.radial_segments = 48
	# Open at the top and seen from inside, so the walls have to face inwards.
	var material: StandardMaterial3D = _palette.bowl_dark().duplicate()
	material.cull_mode = BaseMaterial3D.CULL_FRONT
	var node := MeshInstance3D.new()
	node.name = "DrainWell"
	node.mesh = mesh
	node.material_override = material
	var centre := _bowl_centre()
	node.position = Vector3(
		centre.x, centre.y - DRAIN_WELL_DEPTH * 0.5 + 0.02, centre.z)
	node.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
	root.add_child(node)


func _build_bowl_cradle(root: Node3D) -> void:
	## The metallic support shell: a hoop under the vessel and legs to the
	## floor of the room. Without it the bowl is a shape hanging in the air.
	var hoop_rho := 0.86
	var hoop_y := bowl_surface_y(hoop_rho) - BOWL_GLASS_DROP - 0.20
	root.add_child(_ring("Cradle", hoop_rho, 0.16, hoop_y, 0.0,
		_palette.structure(false, true)))

	# Radial ribs from the hoop in towards the drain, following the dish.
	# The brief asks for metallic structural support under the bowl and this
	# is it: from any angle low enough to see beneath the lip, the vessel is
	# sitting in a frame rather than floating.
	for index in BOWL_LEGS:
		var rib_angle := TAU * (float(index) + 0.5) / float(BOWL_LEGS)
		var inner := _bowl_point(0.34, rib_angle, BOWL_GLASS_DROP + 0.10)
		var outer := _bowl_point(hoop_rho, rib_angle, BOWL_GLASS_DROP + 0.20)
		var delta := outer - inner
		var rib := _box("Rib%d" % index,
			Vector3(Vector2(delta.x, delta.z).length(), 0.13, 0.20),
			(inner + outer) * 0.5, _palette.bowl_shell())
		rib.rotation.y = -atan2(delta.z, delta.x)
		rib.rotation.z = atan2(delta.y, Vector2(delta.x, delta.z).length())
		root.add_child(rib)

	var centre := _bowl_centre()
	var radius := hoop_rho * _bowl_r / PIXELS_PER_UNIT
	for index in BOWL_LEGS:
		# Offset half a step so no leg stands on the centre line, where it
		# would sit directly under the drain and in front of the throat.
		var angle := TAU * (float(index) + 0.5) / float(BOWL_LEGS)
		var x := centre.x + radius * cos(angle)
		var z := centre.z + radius * sin(angle)
		var length := hoop_y - VOID_FLOOR_Y
		root.add_child(_box("Leg%d" % index,
			Vector3(0.34, length, 0.34),
			Vector3(x, hoop_y - length * 0.5, z),
			_palette.structure()))
		root.add_child(_box("LegFoot%d" % index,
			Vector3(0.44, 0.24, 0.44),
			Vector3(x, VOID_FLOOR_Y + 0.12, z),
			_palette.structure(false, true)))

	# A collar low on the legs, so they read as one frame rather than six
	# unrelated posts.
	root.add_child(_ring("CradleBrace", hoop_rho, 0.07, VOID_FLOOR_Y + 4.2,
		0.0, _palette.structure(true)))


func _build_bowl_lights(root: Node3D) -> void:
	## The one place on the machine allowed its own colour, and it is kept
	## quiet: a cool light down in the drain and a violet one across the rim,
	## both well under the energy that would flatten the curve they are lit by.
	var drain := OmniLight3D.new()
	drain.name = "DrainLight"
	drain.light_color = NeonMaterials.CYAN
	drain.light_energy = 1.1
	drain.omni_range = 5.2
	drain.omni_attenuation = 1.4
	drain.shadow_enabled = false
	var centre := _bowl_centre()
	drain.position = Vector3(centre.x, centre.y + 0.45, centre.z)
	root.add_child(drain)

	var rim := OmniLight3D.new()
	rim.name = "RimLight"
	rim.light_color = NeonMaterials.VIOLET
	rim.light_energy = 0.55
	rim.omni_range = 9.0
	rim.omni_attenuation = 1.6
	rim.shadow_enabled = false
	rim.position = Vector3(centre.x, H_RIM + 1.9, centre.z + 1.2)
	root.add_child(rim)


# --- the start platform ---------------------------------------------------

func _build_start_platform() -> void:
	## A raised deck with a shuttered lip, standing on its own frame.
	##
	## The release is worth a note, because the mapping decides what it looks
	## like. Simulation y runs down the course and becomes world Z, so a
	## marble falling in the simulation travels *forward and down* on screen.
	## The gate in the simulation is the platform floor, removed on one tick;
	## on screen that is sixteen marbles rolling forward over the lip
	## together, which is why the drawn gate is a barrier across the front and
	## not a trapdoor underneath. Same event, and the honest picture of it.
	var root := Node3D.new()
	root.name = "StartPlatform"
	add_child(root)

	var back := _platform_top - PLATFORM_OVERHANG
	var samples := [
		Vector3(_platform_left, _platform_right, back),
		Vector3(_platform_left, _platform_right, _gate_y),
	]
	var deck := _widen(samples, -DECK_MARGIN, DECK_MARGIN)
	root.add_child(_solid_ribbon("Deck", deck, 0.0, PLATFORM_THICKNESS,
		[_palette.track_top(), _palette.track_side(), _palette.track_web()]))

	root.add_child(_solid_ribbon("Panel", _inset(deck, PANEL_INSET),
		PANEL_DEPTH, DECK_THICKNESS * 0.5,
		[_palette.track_top(true), _palette.track_side(),
			_palette.track_web()], false))
	root.add_child(_solid_ribbon("Spine", _inset(deck, PANEL_SPINE),
		PANEL_DEPTH * 2.0, DECK_THICKNESS * 0.5,
		[_palette.track_side(), _palette.track_side(),
			_palette.track_web()], false))

	var rail_px := RAIL_WIDTH * PIXELS_PER_UNIT
	var light_px := RAIL_LIGHT_INSET * PIXELS_PER_UNIT
	for side in [-1.0, 1.0]:
		var tag := "L" if side < 0.0 else "R"
		root.add_child(_solid_ribbon("Rail%s" % tag,
			_band(deck, side, 0.0, rail_px), RAIL_HEIGHT, RAIL_HEIGHT + 0.06,
			[_palette.rail(), _palette.rail(), _palette.track_web()]))
		root.add_child(_solid_ribbon("Edge%s" % tag,
			_band(deck, side, light_px, rail_px - light_px),
			RAIL_HEIGHT + RAIL_LIGHT_HEIGHT, RAIL_LIGHT_HEIGHT,
			[_palette.edge_light(), _palette.edge_light(),
				_palette.edge_light()], false))

	# Lane grooves let into the deck, running the way the marbles will travel.
	# Along, not across: a line drawn across a deck reads as a rung and puts
	# the frame straight back into diagram territory, while a line down the
	# direction of travel is what a machined floor actually looks like.
	var half_span := (_platform_right - _platform_left) * 0.5
	for index in GRID_LANES:
		var lane := _platform_left + (_platform_right - _platform_left) \
			* (float(index) + 0.5) / float(GRID_LANES)
		root.add_child(_box("Lane%d" % index,
			Vector3(0.035, 0.02, to_units(_gate_y - back) - 0.10),
			Vector3(to_units(lane - _course_width * 0.5), H_START - 0.004,
				to_units((back + _gate_y) * 0.5)),
			_palette.structure(true), false))

	_build_start_frame(root, back, half_span)
	_build_start_gate(root)
	_build_start_sign(root, back)


func _build_start_frame(root: Node3D, back: float, half_span: float) -> void:
	## The dark support structure under the deck. The brief asks for it by
	## name, and it is what makes a platform read as suspended in a machine
	## rather than as a rectangle floating in a dark frame.
	var housing := _box("Housing",
		Vector3(to_units(_platform_right - _platform_left) * 0.86,
			PLATFORM_HOUSING, to_units(_gate_y - back) * 0.80),
		Vector3(0.0, H_START - PLATFORM_THICKNESS - PLATFORM_HOUSING * 0.5,
			to_units((back + _gate_y) * 0.5)),
		_palette.structure())
	root.add_child(housing)

	var top := H_START - PLATFORM_THICKNESS - PLATFORM_HOUSING
	var middle := to_units((back + _gate_y) * 0.5)
	var reach := to_units(_gate_y - back) * 0.34
	for raw_x in [-1.0, 1.0]:
		var sx := float(raw_x)
		for raw_z in [-1.0, 1.0]:
			var sz := float(raw_z)
			var x := sx * to_units(half_span) * 0.82
			var z := middle + sz * reach
			var length := top - VOID_FLOOR_Y
			root.add_child(_box("Leg%d_%d" % [int(sx), int(sz)],
				Vector3(0.30, length, 0.30),
				Vector3(x, top - length * 0.5, z),
				_palette.structure()))
			root.add_child(_box("Foot%d_%d" % [int(sx), int(sz)],
				Vector3(0.50, 0.26, 0.50),
				Vector3(x, VOID_FLOOR_Y + 0.13, z),
				_palette.structure(false, true)))
		# Two cross-braces per side, at different depths, so the frame has a
		# silhouette instead of four parallel lines.
		for raw_level in [2.6, 6.4]:
			var level := float(raw_level)
			root.add_child(_box("Tie%d_%d" % [int(sx), int(level * 10.0)],
				Vector3(0.16, 0.16, to_units(_gate_y - back) * 0.70),
				Vector3(sx * to_units(half_span) * 0.82, top - level, middle),
				_palette.structure(false, true)))


func _build_start_gate(root: Node3D) -> void:
	## The release: blades standing across the lip, dropping into the housing.
	##
	## They are animated to *finish* moving on the tick the simulation removes
	## the floor, so a marble is never drawn passing through a blade that has
	## not got out of the way yet. Nothing here decides when the race starts -
	## the replay does, and this reads it.
	var housing_z := to_units(_gate_y) + GATE_DEPTH * 0.6
	root.add_child(_box("GateHousing",
		Vector3(to_units(_platform_right - _platform_left) + 0.5,
			GATE_HOUSING, GATE_DEPTH * 2.2),
		Vector3(0.0, H_START - GATE_HOUSING * 0.5 - 0.02, housing_z),
		_palette.structure()))

	var span := _platform_right - _platform_left
	for index in GATE_BLADES:
		var centre := _platform_left + span * (float(index) + 0.5) \
			/ float(GATE_BLADES)
		var width := to_units(span) / float(GATE_BLADES) - GATE_GAP
		var blade := Node3D.new()
		blade.name = "Blade%d" % index
		blade.position = Vector3(
			to_units(centre - _course_width * 0.5), H_START, to_units(_gate_y))
		root.add_child(blade)

		# A polished face on a graphite frame, so a blade reads as a machined
		# shutter rather than as a dark line across the deck.
		blade.add_child(_box("Body", Vector3(width, GATE_HEIGHT, GATE_DEPTH),
			Vector3(0.0, GATE_HEIGHT * 0.5, 0.0),
			_palette.structure(false, true)))
		blade.add_child(_box("Face",
			Vector3(width * 0.90, GATE_HEIGHT * 0.72, GATE_DEPTH * 0.45),
			Vector3(0.0, GATE_HEIGHT * 0.46, -GATE_DEPTH * 0.34),
			_palette.rail()))
		blade.add_child(_box("Light",
			Vector3(width * 0.86, GATE_LIGHT, GATE_DEPTH * 0.55),
			Vector3(0.0, GATE_HEIGHT - GATE_LIGHT * 0.5, 0.0),
			_palette.start_light(), false))

		_shutter_leaves.append(blade)
		_shutter_home.append(H_START)


func _build_start_sign(root: Node3D, back: float) -> void:
	## The cyan and white treatment. The one place on this machine with text
	## on it, and the brightest thing in the first second of the shot.
	var z := to_units(back) - 0.35
	var half := to_units(_platform_right - _platform_left) * 0.30
	var sign := Node3D.new()
	sign.name = "StartSign"
	sign.position = Vector3(0.0, H_START, z)
	root.add_child(sign)

	for side in [-1.0, 1.0]:
		sign.add_child(_box("Post%d" % int(side),
			Vector3(0.16, SIGN_HEIGHT, 0.16),
			Vector3(side * half, SIGN_HEIGHT * 0.5, 0.0),
			_palette.structure(false, true)))

	var panel := Node3D.new()
	panel.name = "Panel"
	panel.position = Vector3(0.0, SIGN_HEIGHT - SIGN_PANEL.y * 0.5, 0.0)
	# Leaned back towards the lens, so the face is square to a camera looking
	# down at it rather than edge-on.
	panel.rotation_degrees = Vector3((90.0 - _elevation) * 0.85, 0.0, 0.0)
	sign.add_child(panel)

	panel.add_child(_box("Frame",
		Vector3(half * 2.0 + 0.16, SIGN_PANEL.y + 0.10, SIGN_PANEL.z),
		Vector3.ZERO, _palette.structure(false, true)))
	panel.add_child(_box("Face",
		Vector3(half * 2.0, SIGN_PANEL.y, SIGN_PANEL.z * 0.5),
		Vector3(0.0, 0.0, -SIGN_PANEL.z * 0.4),
		_palette.start_light(), false))

	var label := Label3D.new()
	label.name = "Text"
	label.text = "START"
	label.font_size = 220
	label.pixel_size = 0.0029
	label.shaded = false
	label.double_sided = false
	label.modulate = Color(0.03, 0.10, 0.16)
	label.outline_size = 0
	label.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	label.vertical_alignment = VERTICAL_ALIGNMENT_CENTER
	label.position = Vector3(0.0, 0.0, -SIGN_PANEL.z * 0.66)
	label.rotation_degrees = Vector3(0.0, 180.0, 0.0)
	panel.add_child(label)


# --- the room -------------------------------------------------------------

func _build_room() -> void:
	## A dark chamber the machine stands in, and a floor a long way below it.
	##
	## Deliberately not a slab under the track. The brief is explicit that the
	## machine has to have visible space around and underneath it, and that is
	## the one thing a background plane immediately behind the course cannot
	## give: the floor is nineteen units down, the two ranks of columns are
	## eleven and fifteen and a half units out - the near rank clearing the
	## bowl's lip, which reaches 5.6 - and everything between them is air that
	## the pillars and the bowl's legs cross.
	var root := Node3D.new()
	root.name = "Room"
	add_child(root)

	var top := _course_top - ROOM_OVERRUN_TOP
	var bottom := _course_bottom + ROOM_OVERRUN_BOTTOM
	var length := to_units(bottom - top)
	var centre := to_units((top + bottom) * 0.5)

	root.add_child(_box("Floor", Vector3(70.0, 0.8, length),
		Vector3(0.0, VOID_FLOOR_Y - 0.4, centre), _palette.void_floor(), false))

	# Two ranks of columns at different distances. One rank gives the camera
	# a rate to sweep past; two at different distances give a *comparison*,
	# and the comparison is the parallax cue a viewer actually reads.
	_build_columns(root, "Far", COLUMN_FAR_X, COLUMN_FAR_SPACING,
		COLUMN_FAR_SIZE, _palette.structure(true), top, bottom)
	_build_columns(root, "Near", COLUMN_NEAR_X, COLUMN_NEAR_SPACING,
		COLUMN_NEAR_SIZE, _palette.structure(false, true), top, bottom)
	_build_wall_strips(root, top, bottom)
	_build_gantries(root, top, bottom)


func _build_gantries(root: Node3D, top: float, bottom: float) -> void:
	## Beams across the room, well behind and well above the machine.
	##
	## Distant machinery. Brackets reaching in from each wall and stopping
	## well short of the middle, never a beam right across.
	##
	## The first version ran them the full width and it was the race scene's
	## gantry lesson over again in a new place: a horizontal bar across a
	## portrait frame reads as letterboxing, and two of them read as a fault
	## in the render. Reaching in from the sides they still say the machine is
	## standing inside a structure, and they cross nothing.
	var count := maxi(1, int((bottom - top) / GANTRY_SPACING))
	for index in count:
		var y := top + (float(index) + 0.5) * (bottom - top) / float(count)
		var height := deck_height(_course_width * 0.5, y)
		for raw_side in [-1.0, 1.0]:
			var side := float(raw_side)
			root.add_child(_box("Gantry%d_%d" % [index, int(raw_side)],
				Vector3(GANTRY_REACH, 0.40, 0.60),
				Vector3(side * (COLUMN_FAR_X - GANTRY_REACH * 0.5),
					height + GANTRY_HIGH, to_units(y)),
				_palette.structure(true), false))


func _build_columns(root: Node3D, tag: String, offset: float, spacing: float,
		size: Vector3, material: StandardMaterial3D,
		top: float, bottom: float) -> void:
	## One rank of columns down each side, as a single MultiMesh.
	##
	## Two hundred boxes would be two hundred draw calls for scenery nobody
	## looks at directly. As instances of one mesh they are one.
	var count := int(to_units(bottom - top) / spacing)
	if count < 2:
		return

	var mesh := BoxMesh.new()
	mesh.size = size

	var multi := MultiMesh.new()
	multi.transform_format = MultiMesh.TRANSFORM_3D
	multi.mesh = mesh
	multi.instance_count = count * 2

	for index in count:
		var z := to_units(top) + float(index) * spacing
		# The columns follow the machine down, so the room descends with it
		# rather than crossing every level at one height.
		var height := deck_height(_course_width * 0.5, z * PIXELS_PER_UNIT)
		for side_index in 2:
			var side := -1.0 if side_index == 0 else 1.0
			multi.set_instance_transform(index * 2 + side_index,
				Transform3D(Basis(), Vector3(
					side * offset, height + size.y * 0.5 - COLUMN_SINK, z)))

	var node := MultiMeshInstance3D.new()
	node.name = "Columns%s" % tag
	node.multimesh = multi
	node.material_override = material
	node.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
	root.add_child(node)


func _build_wall_strips(root: Node3D, top: float, bottom: float) -> void:
	## A lit line down each far wall. Low energy: this is depth, not a light.
	var runs := maxi(1, int((bottom - top) / 600.0))
	var span := (bottom - top) / float(runs)
	for side in [-1.0, 1.0]:
		for index in runs:
			var y := top + (float(index) + 0.5) * span
			var height := deck_height(_course_width * 0.5, y)
			root.add_child(_box("Strip%d_%d" % [int(side), index],
				Vector3(0.10, 0.09, to_units(span) - 0.6),
				Vector3(side * (COLUMN_FAR_X - COLUMN_FAR_SIZE.x * 0.6),
					height + 2.6, to_units(y)),
				_palette.strip(index % 3 == 1), false))


# --- racers ---------------------------------------------------------------

func _build_racers() -> void:
	## Premium glossy marbles, and nothing stuck to them.
	##
	## No trail, no glow, no impact ring. The brief asks for architecture and
	## art direction to be judged first, and every one of those would be
	## judged instead: a trail is the brightest thing in a dark frame, and a
	## glow on a sphere removes the terminator that makes it a sphere.
	var root := Node3D.new()
	root.name = "Racers"
	add_child(root)

	var flags: RefCounted = NeonFlags.new() if _countries else null

	for index in _racer_meta.size():
		var meta: Dictionary = _racer_meta[index]
		var radius := to_units(float(meta.get("radius", 30.0)))
		var color := _color_of(meta)
		var racer_id := int(meta.get("id", 0))

		var pivot := Node3D.new()
		pivot.name = "Racer%d" % racer_id
		root.add_child(pivot)

		var mesh := SphereMesh.new()
		mesh.radius = radius
		mesh.height = radius * 2.0
		mesh.radial_segments = 48
		mesh.rings = 24

		var material: StandardMaterial3D = _palette.racer(color)
		if flags != null and index < flags.country_count():
			material = _palette.racer_textured(
				flags.texture(index), flags.name_of(index))

		var sphere := MeshInstance3D.new()
		sphere.name = "Body"
		sphere.mesh = mesh
		sphere.material_override = material
		pivot.add_child(sphere)

		_build_badge(pivot, racer_id, color, radius)

		_racer_nodes.append(pivot)
		_racer_spheres.append(sphere)
		_racer_radius.append(radius)


func _build_badge(pivot: Node3D, racer_id: int, color: Color,
		radius: float) -> void:
	## The racer's number, small, above the marble.
	##
	## Above rather than on it: a number painted on a rolling sphere spends
	## most of its time on the far side, and the moment a viewer wants to read
	## it is the moment sixteen marbles are in a bowl together. Deliberately
	## smaller than the race scene's - the brief asks for the marbles to stay
	## dominant, and a plate the size of the ball it labels is a label with a
	## marble attached.
	var badge := Node3D.new()
	badge.name = "Badge"
	badge.position = Vector3(0.0, radius + BADGE_RISE, 0.0)
	pivot.add_child(badge)

	var label := Label3D.new()
	label.name = "Number"
	label.text = str(racer_id + 1)
	label.font_size = BADGE_FONT_SIZE
	label.pixel_size = BADGE_PIXEL_SIZE
	label.billboard = BaseMaterial3D.BILLBOARD_ENABLED
	label.shaded = false
	label.double_sided = true
	label.alpha_cut = Label3D.ALPHA_CUT_DISCARD
	label.modulate = color.lightened(0.62)
	label.outline_modulate = Color(0.0, 0.0, 0.0, 0.85)
	label.outline_size = BADGE_OUTLINE
	label.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	label.vertical_alignment = VERTICAL_ALIGNMENT_CENTER
	label.render_priority = 2
	label.outline_render_priority = 1
	badge.add_child(label)


func _color_of(meta: Dictionary) -> Color:
	var raw: Variant = meta.get("color", [])
	if raw is Array and (raw as Array).size() >= 3:
		var rgb: Array = raw
		return Color8(int(rgb[0]), int(rgb[1]), int(rgb[2]))
	return Color.WHITE


func _update_racers(current: Array, upcoming: Array, blend: float) -> void:
	for index in _racer_nodes.size():
		if index >= current.size():
			continue
		var now: Dictionary = current[index]
		var soon: Dictionary = upcoming[index] if index < upcoming.size() else now
		var pivot := _racer_nodes[index]

		# A retired racer was taken out of the simulation's space, so it is
		# taken out of the picture rather than left lying on the machine.
		if bool(now.get("retired", false)):
			pivot.visible = false
			continue
		pivot.visible = true

		# Interpolation is cosmetic: the replay data is never modified.
		var x := lerpf(float(now.get("x", 0.0)), float(soon.get("x", 0.0)), blend)
		var y := lerpf(float(now.get("y", 0.0)), float(soon.get("y", 0.0)), blend)
		var spin := lerp_angle(
			deg_to_rad(float(now.get("rotation_degrees", 0.0))),
			deg_to_rad(float(soon.get("rotation_degrees", 0.0))),
			blend)

		pivot.position = to_world(x, y, _racer_radius[index])
		# A racer rolls about the axis out of the simulation plane, which is
		# world Y, and the plane is mirrored - so the angle is negated.
		_racer_spheres[index].rotation.y = -spin


func _update_gate(tick: float) -> void:
	## Drop the blades so they are clear exactly as the floor is removed.
	if _shutter_leaves.is_empty() or _gate_tick < 0.0:
		return
	var window := SHUTTER_SECONDS * _physics_hz
	var progress := clampf((tick - (_gate_tick - window)) / window, 0.0, 1.0)
	# Accelerating rather than easing out: a gate that snaps clear reads as
	# sprung, and a synchronised start wants the last instant to be the fast
	# one.
	var travel := progress * progress * GATE_HEIGHT * SHUTTER_TRAVEL
	for index in _shutter_leaves.size():
		var blade := _shutter_leaves[index]
		blade.position.y = _shutter_home[index] - travel
		blade.visible = progress < 1.0


# --- playback -------------------------------------------------------------

func present(tick: float) -> void:
	## Show the machine as it stood at `tick`, in simulation ticks.
	if _frames.size() < 1:
		return
	var last := float(_frames.size() - 1)
	var playhead := clampf(tick / _ticks_per_frame, 0.0, last)
	var whole := roundf(playhead)
	if absf(playhead - whole) < PLAYHEAD_SNAP:
		playhead = whole

	var index := int(floor(playhead))
	var next_index := mini(index + 1, _frames.size() - 1)
	var blend := playhead - float(index)

	var frame: Dictionary = _frames[index]
	var next_frame: Dictionary = _frames[next_index]

	_update_camera(frame, next_frame, blend)
	_update_racers(frame.get("racers", []), next_frame.get("racers", []), blend)
	_update_gate(tick)
